src/components.d.ts
src/components/og-expander/og-expander.e2e.ts
src/components/og-expander/og-expander.scss
src/components/og-expander/og-expander.tsx
src/components/og-expander/readme.md
src/index.html
src/styles/themes/dark.theme.scss

Ftr expander

---

src/components/og-dialog/og-confirm-dialog/og-confirm-dialog.e2e.ts
src/components/og-dialog/og-dialog.e2e.ts
src/components/og-dialog/og-success-dialog/og-success-dialog.e2e.ts

Signed-off-by: Tobias Dobbrunz <tobias.dobbrunz@maximago.de>
Please include a summary of the change and which issue is fixed. 

chore: add og-dialog tests

---

src/components/og-textarea/og-textarea.scss

Height of default textarea is 4 lines, focused 5 lines

Fix textarea

---

CHANGELOG.md
package.json
src/components/og-combobox/og-combobox.tsx

Scrolling on parent element of combobox did not close flyout.

Fix combobox scrolling

---

CHANGELOG.md
package.json
src/components/og-list/og-list.tsx

Values on list items are only added to the DOM if value is available

Fix listitem value

---

src/components/og-combobox/og-combobox.scss
src/components/og-combobox/og-combobox.tsx
src/components/og-form-item/og-form-item.scss

Update light and dark theme styles.

update light and dark theme of <og-combobox>

---

src/components/og-combobox/og-combobox.tsx

fixed: When content of combobox flyout is scrolled to the top or bottom, next scroll event will scroll window content and will close combobox flyout.

Fix combobox scrolling 2

---

src/components/og-toggle-switch/og-toggle-switch.scss

Update light and dark theme of <og-toggle-switch>

Fix og toggleswitch styles

---

src/components.d.ts
src/components/og-list-item/og-list-item.e2e.ts
src/components/og-list-item/og-list-item.scss
src/components/og-list-item/og-list-item.tsx
src/components/og-list-item/readme.md
src/components/og-list/og-list.e2e.ts
src/components/og-list/og-list.scss
src/components/og-list/og-list.tsx
src/components/og-list/readme.md

- New feature (a non-breaking change)
Introduce a separate component for a list item.

feat(og-list-item): introduce own component for a list item

---

readme.md

added npm version tag to project readme

add npm version badge

---

rollup-plugins/helpers/add-css-vars-default-value.js
rollup-plugins/orgenic-ui-post-processing.js

Extended documentation for components:
* added column for default value to CSS variable table

docs: add css var default values to readmes

---

src/components/og-card/og-card.scss
src/components/og-form-item/og-form-item.tsx
src/components/og-input/og-number-input/og-number-input.tsx
src/index.html
src/styles/themes/_font.scss
src/styles/themes/dark.theme.scss
src/styles/themes/light.theme.scss

Ftr typographie

---

src/components/og-form-item/og-form-item.tsx

A formitem with number input handles value "0" as empty. The form item label was positioned in the wrong position. This behaviour is fixed with this PR.

fix(input): fix handling 0 in number input

---

src/index.html

fix: heading tag

---

src/components.d.ts
src/components/og-combobox/og-combobox.tsx
src/components/og-combobox/readme.md
src/components/og-datepicker/og-datepicker.tsx
src/components/og-form-item/og-form-item.tsx
src/components/og-internal-calendar/og-internal-calendar.tsx
src/components/og-internal-calendar/readme.md
src/index.html
src/utils/dom-utils.ts

fix(datepicker): fix bug when used in FormItem #69

---

CHANGELOG.md
package-lock.json
package.json
rollup-plugins/orgenic-ui-post-processing.js
src/components.d.ts
src/components/og-calendar/og-calendar.tsx
src/components/og-combobox/og-combobox.tsx
src/components/og-combobox/readme.md
src/components/og-datepicker/og-datepicker.tsx
src/components/og-form-item/og-form-item.tsx
src/components/og-internal-calendar/og-internal-calendar.tsx
src/components/og-internal-calendar/readme.md
src/index.html
src/utils/dom-utils.ts
src/utils/moment-locale-loader.ts

* fix parsing dates according to locale
* fix empty state handling in og-formitem
* fix flyout position in small windows
* fix resolving locales

Prepare v0.3.1

---

src/components/og-card/og-card.scss
src/components/og-combobox/og-combobox.scss
src/components/og-datepicker/og-datepicker.scss
src/components/og-dialog/og-dialog.scss
src/components/og-textarea/og-textarea.scss

- [x ] Other (a non-breaking change - please add details in the description section)
Improve browser scroll behaviour when using "overflow" property

fix: improve browser scroll behaviour

---

src/components/og-dialog/og-dialog.tsx

Check event target on keydown.

Fix og dialog scrollhandler

---

src/components/og-card/og-card.scss
src/components/og-combobox/og-combobox.scss
src/components/og-combobox/og-combobox.spec.ts
src/components/og-combobox/og-combobox.tsx
src/components/og-datepicker/og-datepicker.scss
src/components/og-datepicker/og-datepicker.tsx
src/components/og-dialog/og-dialog.scss
src/components/og-textarea/og-textarea.scss

Fix styling issues with translateZ behaviour related to og-combobox.
Fix event handling in og-datepicker.

Fix dropdown trigger event

---

src/components/og-input/og-input.scss

Please include a summary of the change and which issue is fixed.

Feat og input texttransform

---

src/components/og-button/og-button.scss
src/examples/Button.html

feat: add new button type 'outline'

---

src/components/og-combobox/og-combobox.tsx
src/components/og-datepicker/og-datepicker.tsx

fix: flyout position

---

src/components.d.ts
src/components/og-list/og-list.tsx
src/examples/List.html

Signed-off-by: jfu-maximago <jfu@maximago.de>
<og-list> supports multiselect and multi-pre-selection

feat: implement multi select

---

package.json
src/components/og-list/og-list.spec.ts
src/components/og-list/og-list.tsx

- [x ] Bug fix (a non-breaking change which fixes an issue - please add the issue reference in the description section)
Multiselection does not work for og-list. The contained Set can't be cast to an array.

og-list - multiselection fix

---

CHANGELOG.md
package-lock.json
package.json

Signed-off-by: Tobias Dobbrunz <tobias.dobbrunz@maximago.de>
Please include a summary of the change and which issue is fixed. 

docs: update version number and changelog

---

src/components/og-list/og-list.tsx

- x ] Bug fix (a non-breaking change which fixes an issue - please add the issue reference in the description section)
Rerenders items when one of them changes.

Fix og list

---

src/components/og-calendar/og-calendar.scss
src/components/og-datepicker/og-datepicker.scss
src/components/og-datepicker/og-datepicker.tsx

Update flyout position always with realtime values.
Supports now transform: translate()

Fix og calender position

---

src/components/og-internal-calendar/interfaces/og-calendar-date-decorator.ts

Signed-off-by: Tobias Dobbrunz <tobias.dobbrunz@maximago.de>
Fixes an issue in typescript projects, throwing an error, when using orgenic-ui.

fix: momentjs issue in typescript projects

---

package-lock.json
package.json

Signed-off-by: Tobias Dobbrunz <tobias.dobbrunz@maximago.de>
Updates npm packages to fix security issues

fix: npm security issues
